### ISSUE TITLE
Project does not build or serve

### ISSUE THREAD

**Issue by SanketDG** [WebPraktikos/universal-resume#9]
This is probably something on my end but I can't seem to get none of the commands working after `npm install`

```shell
➜ npm run build

> universal-resume-template@3.0.0 build /home/sanketdg/projects/universal-resume
> cross-env NODE_ENV=build postcss ./tailwind.css -o docs/build.css

Error: Failed to find 'docs/FiraGo.css'
  in [
    /home/sanketdg/projects/universal-resume
  ]
    at /home/sanketdg/projects/universal-resume/node_modules/postcss-import/lib/resolve-id.js:35:13
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! universal-resume-template@3.0.0 build: `cross-env NODE_ENV=build postcss ./tailwind.css -o docs/build.css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the universal-resume-template@3.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sanketdg/.npm/_logs/2020-04-05T20_24_33_112Z-debug.log

```
```
➜ npm run serve

> universal-resume-template@3.0.0 serve /home/sanketdg/projects/universal-resume
> concurrently "postcss ./tailwind.css -o docs/build.css --watch"  "live-server ./docs "

[0] Error: Failed to find 'docs/FiraGo.css'
[0]   in [
[0]     /home/sanketdg/projects/universal-resume
[0]   ]
[0]     at /home/sanketdg/projects/universal-resume/node_modules/postcss-import/lib/resolve-id.js:35:13
[0] postcss ./tailwind.css -o docs/build.css --watch exited with code 1
^C[1] live-server ./docs  exited with code SIGINT
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! universal-resume-template@3.0.0 serve: `concurrently "postcss ./tailwind.css -o docs/build.css --watch"  "live-server ./docs "`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the universal-resume-template@3.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sanketdg/.npm/_logs/2020-04-05T20_24_47_755Z-debug.log
```

**Comment by WebPraktikos** [comment]
Hey, thanks for reporting! I’ve noticed the same issue when running build on the server. There’s no issues on Windows. As I can see, you are running Linux, right?

**Comment by WebPraktikos** [comment]
Renaming `FiraGo.css` to` fira-go.css` fixes the issue :man_shrugging:
